{
 "title": "Observability dashboard",
 "description": "example of dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Latency histogram",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket[$__rate_interval])) by (le))",
     "legendFormat": "Latency"
    }
   ]
  },
  {
   "title": "Request per time",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total[$__rate_interval]))",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Logs volume",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by (detected_level) (count_over_time({service_name=\"observability\"} [$__auto]))",
     "legendFormat": "{{detected_level}}"
    }
   ]
  },
  {
   "title": "Gauge per path",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (handler) (rate(http_requests_total[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Logs table",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{service_name=\"observability\"} | label_format level=detected_level"
    }
   ]
  },
  {
   "title": "Top 5 paths más lentos",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(5, sum by (handler) (rate(http_requests_total{status=~\"5..\"}[5m])))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}