model_list:
  - model_name: gpt-4o
    litellm_params:
      model: openai/gpt-4o
      api_base: "https://eu.api.openai.com/v1"

general_settings:
  master_key: "sk-1234"
  otel: true # Habilita la exportación a OTEL

environment_variables:
  OTEL_ENDPOINT: "http://host.docker.internal:4317" # Ajusta si el colector está en otro contenedor
  OTEL_SERVICE_NAME: "litellm-proxy"
