apiVersion: 1

datasources:
  - name: jaeger
    type: jaeger
    access: proxy
    url: http://jaeger:4318

  - name: loki
    type: loki
    access: proxy
    url: http://loki:3100

  - name: prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true

  - name: tempo
    type: tempo
    access: proxy
    url: http://tempo:3200
    jsonData:
      tracesToLogsV2:
        datasourceUid: loki
        filterBySpanID: true
        filterByTraceID: true
      tracesToMetrics:
        datasourceUid: prometheus